In [2]:
print("29.12.2025 Python tekrar başladı")

29.12.2025 Python tekrar başladı


In [3]:
sayilar = [1,2,3,4,5,6]

for s in sayilar:
    if s %2 == 0:
        print(s, 'cift')
    else:
        print(s, 'tek')

1 tek
2 cift
3 tek
4 cift
5 tek
6 cift


In [4]:
def kare_al (x):
    return x * x
for s in sayilar:
    print(kare_al(s))

1
4
9
16
25
36


In [5]:
import numpy as np 

dizi = np.array([1,2,6,4,5,4,2,7,8,9])
print(dizi)
print(dizi[2:5])
print(dizi[dizi>4])

[1 2 6 4 5 4 2 7 8 9]
[6 4 5]
[6 5 7 8 9]


In [6]:
import pandas as pd

df = pd.DataFrame({
    "satis": [52, 67, 100],
    "ziyaret": [110,54,89],
    "donusum": [72,127,81]
})

df

satis  ziyaret  donusum
0     52      110       72
1     67       54      127
2    100       89       81

In [7]:
df.loc[df["satis"] > 60, ["satis", "donusum"]]

satis  donusum
1     67      127
2    100       81

In [10]:
sayilar = [3,7,10,12,15,18]

for s in sayilar:
    if s %3 ==0:print(s,"3'e bolunur")
    else:
        print(s,"3'e bolunmez")

3 3'e bolunur
7 3'e bolunmez
10 3'e bolunmez
12 3'e bolunur
15 3'e bolunur
18 3'e bolunur


In [11]:
def bolunur_mu(x,n):
    return x % n ==0

for s in sayilar:
    print(s,bolunur_mu(s, 4))

3 False
7 False
10 False
12 True
15 False
18 False


In [12]:
def bolunur_mu(x,n):
    return x % n ==0

for s in sayilar:
    print(s,bolunur_mu(s, 12))

3 False
7 False
10 False
12 True
15 False
18 False


In [13]:
import numpy as np

dizi = np.array([1,4,6,8,11,15,18])

In [14]:
dizi

array([ 1,  4,  6,  8, 11, 15, 18])

In [15]:
dizi[2:6]

array([ 6,  8, 11, 15])

In [16]:
dizi[dizi>7]

array([ 8, 11, 15, 18])

In [17]:
dizi[-1]

np.int64(18)

In [18]:
import pandas as pd

df = pd.DataFrame({
    "urun": ['A','B','C','D','E'],
    "satis":[120,80,150,60,200],
    "stok":[30,50,20,80,10]
})
df

urun  satis  stok
0    A    120    30
1    B     80    50
2    C    150    20
3    D     60    80
4    E    200    10

In [19]:
df.loc[df["satis"] > 100, ["urun","satis"]]

urun  satis
0    A    120
2    C    150
4    E    200

In [22]:
df.loc[df["stok"] >= 50, ["urun","stok"]]

urun  stok
1    B    50
3    D    80

In [23]:
df.loc[df["stok"] < 40,:]

urun  satis  stok
0    A    120    30
2    C    150    20
4    E    200    10

In [24]:
dizi[dizi % 2 == 0]

array([ 4,  6,  8, 18])

In [25]:
sayilar = [12, 7, 18, 5, 21, 30, 4]

In [32]:
def ciftleri_bul(liste):
    return [x for x in liste if x % 2 == 0]

def tekleri_bul(liste):
    return [x for x in liste if x %2 != 0]

ciftler = ciftleri_bul(sayilar)
tekler = tekleri_bul(sayilar)

print("Ciftler", ciftler)
print("Tekler", tekler)

Ciftler [12, 18, 30, 4]
Tekler [7, 5, 21]


In [33]:
if len(ciftler) > len(tekler):
    print("cift sayi agirlikli bir liste")
else:
    print("Tek sayi agirlikli bir liste")

cift sayi agirlikli bir liste


In [34]:
import pandas as pd 

df = pd.DataFrame({"sayi":sayilar})
df

sayi
0    12
1     7
2    18
3     5
4    21
5    30
6     4

In [35]:
df["cift_mi"] = df["sayi"] % 2 == 0
df["tek_mi"] =df["sayi"] % 2 != 0
df

sayi  cift_mi  tek_mi
0    12     True   False
1     7    False    True
2    18     True   False
3     5    False    True
4    21    False    True
5    30     True   False
6     4     True   False

In [37]:
ciftler_pd = df.loc[df["cift_mi"], "sayi"].tolist()
tekler_pd = df.loc[df["tek_mi"], "sayi"].tolist()

print("ciftler (pandas):", ciftler_pd)
print("tekler (pandas):", tekler_pd)

if len(ciftler_pd) > len(tekler_pd):
    print("pandas: cift sayi agirlikli")
else:
    print("pandas: tek sayi agirlikli")

ciftler (pandas): [12, 18, 30, 4]
tekler (pandas): [7, 5, 21]
pandas: cift sayi agirlikli


In [38]:
print(df["cift_mi"].value_counts())

cift_mi
True     4
False    3
Name: count, dtype: int64
